services:
  mysql-db:
    image: mysql:8.0
    container_name: appstripe-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appstripe_db
      MYSQL_USER: codefactory
      MYSQL_PASSWORD: apppassword
    ports:
      - "3406:3306"
    # ESTA ES LA ETIQUETA QUE OBLIGA A SPRING BOOT A USAR LOS PARÁMETROS CORRECTOS
    labels:
      org.springframework.boot.jdbc.parameters: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: